services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  # https://community.iotawatt.com/t/getting-started-with-influxdb-and-grafana-using-docker-compose/4981
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=feelhippo
      - DOCKER_INFLUXDB_INIT_PASSWORD=VeryLongPassword123!
      - DOCKER_INFLUXDB_INIT_ORG=symera
      - DOCKER_INFLUXDB_INIT_BUCKET=uwb_telemetry_db
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5J0CC86lbJT1KktGQ1X_16xNvClElpZWrjkI71D66ZAmkg_EHXMwtVz1sSTXLFLH9AZFt8Ltu4iZim0pCzQNlg==
      - DOCKER_INFLUXDB_INIT_RETENTION=1h

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234  #change the password
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '43000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
  client:
    build: ./client
    depends_on:
      - mosquitto
  consumer:
    build: ./consumer
    ports:
      - "3001:3001"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=symera
      - DOCKER_INFLUXDB_INIT_BUCKET=uwb_telemetry_db
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5J0CC86lbJT1KktGQ1X_16xNvClElpZWrjkI71D66ZAmkg_EHXMwtVz1sSTXLFLH9AZFt8Ltu4iZim0pCzQNlg==
    depends_on:
      - influxdb

volumes:
  grafana_data:
  influxdb_data: